### ISSUE TITLE
Week 2 Todo List(due 10/16 Saturday)

### ISSUE THREAD

**Issue by ghost** [Big-Bytez/cse110-fa21-group19#1]
1. Team Branding

- [x] Team Brand
- [x] Team page
- [x] Team intro video

2. Group Bonding Event

- [x] photo of entire team

3. Group Contract 

- [ ] Definition of what is expected to be on the team
- [ ] Definition of how to address situations where group "rules" are not being followed

4. Repo, meeting

- [x] meeting minutes in Repo
- [x] meeting structure
- [ ] short description of the project in README.md
